# https://sceptre.cloudreach.com/latest/docs/stack_group_config.html
project_code: {{ var.project_code | default("atc") }} # aws-tool-comparison
region: {{ var.region | default("eu-west-1") }}

# lambda
GitRepository: https://github.com/bilardi/aws-saving
RepositoryFolder: aws-saving
LambdaName: aws_saving
MemorySize: 512
Runtime: python3.7
Timeout: 300
S3bucket: your-bucket-name
LambdaZipS3key: cli/cloudformation/templates/lambda/code.zip
EvaluationPeriods: 2
Period: 60
Statistic: Average
Threshold: 1

# tags
Saving_EC2: Enabled
Delete_EC2: '0 18 . . .'
Saving_lambda: Disabled
Delete_lambda: '0 18 30 2 .'

# SNS
TopicName: alarms-sns
DisplayName: 'My alarms'
Endpoint: your@email.net
